function kml(lat,lon,name,description)
% Makes a Google Earth kml file containing markers at each latitude -
% longitude pair in the vectors lat and lon.

    fid=fopen('samplelocations.kml','w');
    
    fprintf(fid,['<?xml version="1.0" encoding="UTF-8"?>\n'...
        '<kml xmlns="http://www.opengis.net/kml/2.2">\n<Document>\n'...
        '<name>Sample Locations</name>\n  <open>0</open>\n']);
    fprintf(fid,[...
        '	<Style id="sn_shaded_dot">\n'...
        '		<IconStyle>\n'...
        '			<color>ff3900ff</color>\n'...
        '			<scale>0.6</scale>\n'...
        '			<Icon>\n'...
        '				<href>http://maps.google.com/mapfiles/kml/shapes/shaded_dot.png</href>\n'...
        '			</Icon>\n'...
        '		</IconStyle>\n'...
        '		<ListStyle>\n		</ListStyle>\n'...
        '	</Style>\n'...
        '	<Style id="sh_shaded_dot">\n'...
        '		<IconStyle>\n'...
        '			<color>ff3900ff</color>\n'...
        '			<scale>0.6</scale>\n'...
        '			<Icon>\n'...
        '				<href>http://maps.google.com/mapfiles/kml/shapes/shaded_dot.png</href>\n'...
        '			</Icon>\n'...
        '		</IconStyle>\n'...
        '		<ListStyle>\n		</ListStyle>\n'...
        '	</Style>\n'...
        '	<StyleMap id="msn_shaded_dot">\n'...
        '		<Pair>\n'...
        '			<key>normal</key>\n'...
        '			<styleUrl>#sn_shaded_dot</styleUrl>\n'...
        '		</Pair>\n'...
        '		<Pair>\n'...
        '			<key>highlight</key>\n'...
        '			<styleUrl>#sh_shaded_dot</styleUrl>\n'...
        '		</Pair>\n'...
        '	</StyleMap>']);
    

    for i=1:length(lat)
        fprintf(fid,[...
            '	<Placemark>\n'...
            '		<name>%s</name>\n'...
            '		<description>%s</description>\n'...
            '		<styleUrl>#msn_shaded_dot</styleUrl>\n'...
            '			<scale>0.7</scale>\n'...
            '		<Point>\n'...
            '			<coordinates>%.10f,%.10f,0</coordinates>\n'...
            '		</Point>\n'...
            '	</Placemark>'],...
            name{i},description{i},lon(i),lat(i));
    end
    
    fprintf(fid,'</Document>\n</kml>\n');
    fclose(fid);
end