function kml2(lat,lon,age)
% Makes a Google Earth kml file containing markers at each latitude -
% longitude pair in the vectors lat and lon.

    fid=fopen('samplelocations.kml','w');
    
    fprintf(fid,['<?xml version="1.0" encoding="UTF-8"?>\n'...
        '<kml xmlns="http://www.opengis.net/kml/2.2">\n<Document>\n'...
        '<name>Sample Locations</name>\n  <open>0</open>\n']);
    fprintf(fid,['  <Style id="red-pushpin">\n    <IconStyle>\n      '...
        '<color>ff0000ff</color>\n      <scale>1.3</scale>\n    </IconStyle>\n    '...
        '<LabelStyle>\n      <scale>0.1</scale>\n    </LabelStyle>\n  '...
        '</Style>\n']);
    

    for i=1:length(lat)
        fprintf(fid,['  <Placemark>\n    <name> </name>\n    '...
            '<styleUrl>#red-pushpin</styleUrl>\n    <description> '...
            '%3.2f Ma\n </description>\n    '...
            '<Point>\n      <coordinates>%.10f,%.10f,0</coordinates>\n    </Point>\n  '...
            '</Placemark>\n'],age(i),lon(i),lat(i));
    end
    
    fprintf(fid,'</Document>\n</kml>\n');
    fclose(fid);
end